# Generated by Django 6.0.4 on 2026-05-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='static_image',
            field=models.CharField(blank=True, help_text='Filename in static/images/', max_length=100),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='image',
            field=models.CharField(blank=True, help_text='Filename in static/images/', max_length=100),
        ),
    ]
